# 指定服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# 配置应用名
spring:
  application:
    name: EurekaClientFeign
# 配置tomcat端口
server:
  port: 8764
# 开启断路器hystrix：Feign是自带断路器的,但是默认是关闭的，所在这里需要配置打开
feign:
  hystrix:
    enabled: true