# 指定服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# 设置注册的应用名，在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: EurekaServer
# 配置tomcat端口号
server:
  port: 8762