# 指定服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# 配置应用名
spring:
  application:
    name: EurekaClientRibbon
# 配置tomcat端口
server:
  port: 8765